name: archive

on:
  # Questo workflow si avvia quando il workflow "Build Typst Documentation" termina
  workflow_run:
    workflows: ["Build Typst Documentation"]
    types: [completed]
  # Permette anche di lanciarlo manualmente
  workflow_dispatch:

jobs:
  process_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Avvio dello script di processamento
        run: |
          echo "Avvio dello script di processamento (BOT)"
          python process_files.py

      - name: Commit and push archivio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/archive
          if git diff --cached --quiet; then
            echo "DEBUG: No changes to commit for archivio"
            exit 0
          fi
          git commit -m "Sposta file in archivio (bot)"
          git push origin HEAD:main

      - name: Lista contenuti di documents/archive
        run: ls -R documents/archive

      - name: Upload artifact (report)
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.yml
