name: archive
on:
  workflow_run:
    workflows: ["Build Typst Documentation"]
    types: [completed]
  workflow_dispatch:

jobs:
  process_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Esegui lo script Python per processare i file
        run: |
          echo "Avvio dello script di processamento..."
          python process_files.py
      - name: Lista contenuti di documents/archive
        run: |
          echo "Contenuto di documents/archive:"
          ls -R documents/archive
