name: archive documents to releases
on:
  workflow_run:
    workflows: ["Publish Build to Pages"]
    types: [completed]
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  releases:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: Create release if tag exists
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pushd "documents/${GITHUB_REF_NAME}" 
          zip -r "${GITHUB_REF_NAME}.zip" .
          popd
          mv "documents/${GITHUB_REF_NAME}/${GITHUB_REF_NAME}.zip" .
          gh release create "$GITHUB_REF_NAME" -t "$GITHUB_REF_NAME" "${GITHUB_REF_NAME}.zip"
        env:
          GITHUB_TOKEN: ${{ github.token }}
