name: Build and Sign Typst Documentation

on:
  push:
    branches:
      - main
    # Evitiamo loop ignorando i PDF già generati/firmati
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del TUO repository principale (dove hai i .typ)
      - name: Checkout main repo
        uses: actions/checkout@v3

      # 2. Pull per sincronizzare con main
      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      # 3. Installa la toolchain Rust (necessaria per Typst)
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 4. Installa Typst CLI
      - name: Install Typst CLI
        run: |
          cargo install --locked typst-cli
          typst --version

      # 5. Compila i file .typ in PDF
      - name: Compile all Typst files to PDF
        run: |
          find sources -type f -name "*.typ" | while read -r file; do
            output="documents/$(echo "$file" | sed 's|^sources/||; s|\.typ$|.pdf|')"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done

      # 6. Installa Java (necessario per Maven e jSignPdf)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 7. Clona la repository di jSignPdf (fork intoolswetrust) e compila con Maven
      - name: Clone & build jSignPdf from source
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          git clone https://github.com/intoolswetrust/jsignpdf.git jsignpdf-src
          cd jsignpdf-src
          mvn clean package
          # Controlla che abbia generato correttamente i .jar in target/
          ls -l target

      # 8. Decodifica il certificato dal secret (PKCS#12 in Base64)
      - name: Decode and set up signing certificate
        run: |
          echo "${{ secrets.SIGN_CERT }}" | base64 -d > cert.p12

      # 9. Firma i PDF usando il jar appena compilato
      - name: Digitally sign and remove unsigned PDFs
        env:
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
          JAVA_TOOL_OPTIONS: "--add-opens=java.base/sun.security.pkcs12=ALL-UNNAMED"
        run: |
          # jSignPdf di solito produce un jar principale in "target/JSignPdf-2.3.0.jar" o simile
          # e una cartella "target/lib" con le dipendenze. Adatta se il nome jar è diverso.
          JSIGNPDF_JAR="jsignpdf-src/target/JSignPdf-2.3.0.jar"
          LIB_DIR="jsignpdf-src/target/lib"

          find documents -type f -name "*.pdf" | while read -r pdf; do
            filename=$(basename "$pdf")
            if [[ "$filename" == *_signed.pdf ]]; then
              continue
            fi

            echo "Firmo $pdf con jSignPdf compilato da sorgente..."

            # Includiamo JSignPdf-2.3.0.jar e tutti i .jar in target/lib nella classpath
            java -cp "$JSIGNPDF_JAR:$LIB_DIR/*" net.sf.jsignpdf.JSignPdf \
              -q \
              -kst PKCS12 \
              -ksf cert.p12 \
              -ksp "$SIGN_CERT_PASSWORD" \
              -ts http://timestamp.digicert.com \
              -os _signed \
              "$pdf"

            signed_pdf="${pdf%.pdf}_signed.pdf"
            if [ -f "$signed_pdf" ]; then
              echo "PDF firmato creato: $signed_pdf"
              rm "$pdf"
            else
              echo "ERRORE: Non trovato $signed_pdf, firma fallita?"
              exit 1
            fi
          done

      # 10. Commit e push dei PDF firmati
      - name: Commit and push signed PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "Nessuna modifica da commitare"
            exit 0
          fi
          git commit -m "Aggiorna PDF con firma digitale (jSignPdf compilato da sorgente)"
          git push origin HEAD:main
