name: Build Typst Documentation

on:
  push:
    branches:
      - main
    # Ignora i PDF già generati, così evitiamo loop
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Pull per sincronizzare con main
      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      # 3. Installa la toolchain Rust
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 4. Installa Typst CLI
      - name: Install Typst CLI
        run: |
          cargo install --locked typst-cli
          typst --version

      # 5. Compila tutti i file .typ in PDF
      - name: Compile all Typst files to PDF
        run: |
          # Cerca i file .typ in 'sources/' (sottocartelle incluse)
          find sources -type f -name "*.typ" | while read -r file; do
            # Sostituisce 'sources/... .typ' con 'documents/... .pdf'
            output="documents/$(echo "$file" | sed 's|^sources/||; s|\.typ$|.pdf|')"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done

      # 6. Imposta Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 7. Scarica jSignPdf 2.2.0 da SourceForge
      - name: Download jSignPdf
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget -q https://downloads.sourceforge.net/project/jsignpdf/jsignpdf/2.2.0/jsignpdf-2.2.0.zip -O jsignpdf-2.2.0.zip
          unzip -j jsignpdf-2.2.0.zip "jsignpdf-2.2.0/jsignpdf-2.2.0-jar-with-dependencies.jar" -d .
          mv jsignpdf-2.2.0-jar-with-dependencies.jar jsignpdf.jar

      # 8. Decodifica il certificato dal secret
      - name: Decode and set up signing certificate
        run: |
          # Il certificato (SIGN_CERT) è in Base64, lo decodifichiamo in cert.p12
          echo "${{ secrets.SIGN_CERT }}" | base64 -d > cert.p12

      # 9. Firma digitalmente i PDF
      - name: Digitally sign new PDFs
        env:
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
        run: |
          # Firma i PDF in 'documents/' non ancora firmati (quelli che non finiscono con "_signed.pdf")
          find documents -type f -name "*.pdf" | while read -r pdf; do
            filename=$(basename "$pdf")
            dir=$(dirname "$pdf")

            # Se il file è già firmato, salta
            if [[ "$filename" == *_signed.pdf ]]; then
              echo "Skipping already signed file: $filename"
            else
              base="${filename%.pdf}"
              newfile="${base}_signed.pdf"
              echo "Signing $filename -> $newfile"

              # Firma con jSignPdf, usando la TSA di DigiCert
              java -jar jsignpdf.jar \
                -storetype pkcs12 \
                -keystore cert.p12 \
                -storepass "$SIGN_CERT_PASSWORD" \
                -tsaUrl http://timestamp.digicert.com \
                "$pdf" "$pdf.signed"

              # Se il file firmato è stato creato, rinominalo e rimuovi l'originale
              if [ -f "$pdf.signed" ]; then
                mv "$pdf.signed" "$dir/$newfile"
                rm "$pdf"
              else
                echo "Error signing $pdf"
                exit 1
              fi
            fi
          done

      # 10. Commit e push dei PDF firmati
      - name: Commit and push signed PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update PDFs with digital signature"
          git push origin HEAD:main
