name: Build Typst Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'documents/candidatura/*.pdf'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Pull
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Typst
        run: |
          cargo install --locked typst-cli
          typst --version

      - name: Create PDF folder
        run: mkdir -p documents/candidatura

      - name: Compile
        run: typst compile sources/candidatura/LetteraPresentazione.typ documents/candidatura/LetteraPresentazione.pdf

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/candidatura/release.pdf
          if git diff --cached --quiet; then
            exit 0
          fi
          git commit -m "Aggiorna PDF "
          git push origin HEAD:main
