name: Build and Sign Typst Documentation

on:
  push:
    branches:
      - main
    # Ignora i PDF già generati per evitare loop continui
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona il TUO repository con i .typ
      - name: Checkout main repo
        uses: actions/checkout@v3

      # 2. Pull per sincronizzare con main
      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      # 3. Installa Rust toolchain (necessaria per Typst)
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 4. Installa Typst CLI
      - name: Install Typst CLI
        run: |
          cargo install --locked typst-cli
          typst --version

      # 5. Compila i file .typ in PDF
      - name: Compile all Typst files to PDF
        run: |
          find sources -type f -name "*.typ" | while read -r file; do
            output="documents/$(echo "$file" | sed 's|^sources/||; s|\.typ$|.pdf|')"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done

      # 6. Installa Java (necessaria per Maven e jSignPdf)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 7. Clona SOLO le parti necessarie di intoolswetrust/jsignpdf (shallow + sparse)
      - name: Clone jSignPdf (shallow + sparse)
        run: |
          sudo apt-get update
          sudo apt-get install -y git maven

          # Crea una cartella dedicata e ci spostiamo dentro
          mkdir jsignpdf-src
          cd jsignpdf-src

          # Inizializza un clone shallow e filtra i blob
          git init
          git remote add origin https://github.com/intoolswetrust/jsignpdf.git
          git config core.sparseCheckout true
          git config pull.rebase false

          # Scarica solo l'ultimo commit
          git pull --depth=1 --filter=blob:none origin main

          # Abilita la sparse checkout "cone mode"
          git sparse-checkout init --cone

          # Includi SOLO pom.xml e la cartella jsignpdf
          git sparse-checkout set pom.xml jsignpdf

          # Re-pull per ottenere solo i file richiesti
          git pull --depth=1 --filter=blob:none origin main

          # Mostra cosa abbiamo scaricato (debug)
          ls -R

      # 8. Compila jSignPdf con Maven
      - name: Build jSignPdf from source
        run: |
          cd jsignpdf-src
          mvn clean package
          cd ..
          # Controllo debug del contenuto di target
          ls -R jsignpdf-src/target

      # 9. Decodifica il certificato PKCS#12 dal secret
      - name: Decode signing certificate
        run: |
          echo "${{ secrets.SIGN_CERT }}" | base64 -d > cert.p12

      # 10. Firma i PDF usando il jar compilato
      - name: Digitally sign and remove unsigned PDFs
        env:
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
          JAVA_TOOL_OPTIONS: "--add-opens=java.base/sun.security.pkcs12=ALL-UNNAMED"
        run: |
          # Adatta il nome del jar se necessario (guarda "target/" per confermare)
          JSIGNPDF_JAR="jsignpdf-src/target/JSignPdf-2.3.0.jar"
          LIB_DIR="jsignpdf-src/target/lib"

          find documents -type f -name "*.pdf" | while read -r pdf; do
            filename=$(basename "$pdf")

            # Se già firmato, salta
            if [[ "$filename" == *_signed.pdf ]]; then
              continue
            fi

            echo "Firmo $pdf con jSignPdf compilato da sorgente..."

            # Classpath: jar principale + tutti i jar in target/lib
            java -cp "$JSIGNPDF_JAR:$LIB_DIR/*" net.sf.jsignpdf.JSignPdf \
              -q \
              -kst PKCS12 \
              -ksf cert.p12 \
              -ksp "$SIGN_CERT_PASSWORD" \
              -ts http://timestamp.digicert.com \
              -os _signed \
              "$pdf"

            signed_pdf="${pdf%.pdf}_signed.pdf"
            if [ -f "$signed_pdf" ]; then
              echo "PDF firmato creato: $signed_pdf"
              rm "$pdf"
            else
              echo "ERRORE: Non trovato $signed_pdf, firma fallita?"
              exit 1
            fi
          done

      # 11. Commit e push dei PDF firmati
      - name: Commit and push signed PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "Nessuna modifica da commitare"
            exit 0
          fi
          git commit -m "Aggiorna PDF con firma digitale (jSignPdf compilato da sorgente, shallow/sparse clone)"
          git push origin HEAD:main
