name: Build and Sign Typst Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Typst CLI
        run: |
          cargo install --locked typst-cli
          typst --version

      # Compila tutti i file .typ in PDF
      - name: Compile all Typst files to PDF
        run: |
          find sources -type f -name "*.typ" | while read -r file; do
            output="documents/$(echo "$file" | sed 's|^sources/||; s|\.typ$|.pdf|')"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download jSignPdf 2.3.0
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget -q "https://sourceforge.net/projects/jsignpdf/files/stable/JSignPdf-2.3.0/jsignpdf-2.3.0.zip/download" -O jsignpdf-2.3.0.zip
          unzip -j jsignpdf-2.3.0.zip "jsignpdf-2.3.0/JSignPdf.jar" -d .
          mv JSignPdf.jar jsignpdf.jar

      - name: Decode and set up signing certificate
        run: |
          echo "${{ secrets.SIGN_CERT }}" | base64 -d > cert.p12

      - name: Digitally sign new PDFs
        env:
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
        run: |
          find documents -type f -name "*.pdf" | while read -r pdf; do
            filename=$(basename "$pdf")
            dir=$(dirname "$pdf")

            # Saltiamo i PDF già firmati (con _signed.pdf)
            if [[ "$filename" == *_signed.pdf ]]; then
              echo "Skipping already signed file: $filename"
              continue
            fi

            echo "Signing $filename"

            # Chiamiamo jSignPdf con i parametri vecchi
            java -jar jsignpdf.jar \
              "$pdf" \
              -kst PKCS12 \
              -ksf cert.p12 \
              -ksp "$SIGN_CERT_PASSWORD" \
              -ts http://timestamp.digicert.com \
              -os _signed

            # Esempio: LetteraPresentazione.pdf -> LetteraPresentazione_signed.pdf
            # Verifichiamo se il PDF firmato esiste
            signed_pdf="${pdf%.pdf}_signed.pdf"
            if [ -f "$signed_pdf" ]; then
              echo "Signed PDF created: $signed_pdf"
              # Rimuoviamo l'originale
              rm "$pdf"
            else
              echo "Error signing $pdf"
              exit 1
            fi
          done

      - name: Commit and push signed PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update PDFs with digital signature"
          git push origin HEAD:main
