name: Publish Build to Pages

on:
  workflow_run:
    workflows: ["Build Typst Documentation"]
    types:
      - completed

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: restore
        name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - id: generate
        name: Generate directory listings
        uses: jayanta525/github-pages-directory-listing@main
        with:
          FOLDER: documents
        env:
          TZ: Europe/Rome

      - id: upload
        name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: pages
          path: documents/

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: pages
          branch: gh-pages
