
name: Run workflows in sequence

on:
  push:
    branches:
      - master  # O la branch che preferisci
  workflow_dispatch:

jobs:
  build-typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Typst
        run: echo "Building Typst..."  

  publish-build-to-pages:
    runs-on: ubuntu-latest
    needs: build-typst  # Dipende da 'build-typst', quindi parte solo dopo il completamento del primo job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish build to Pages
        run: echo "Publishing build to GitHub Pages..."  

  archive-documents-to-release:
    runs-on: ubuntu-latest
    needs: publish-build-to-pages  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Archive documents to release
        run: echo "Archiving documents to release..."  
