name: SyncDecision

on:
  workflow_run:
    workflows: ["publish-build-to-pages"]
    types: [completed]

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Wiki Repository
        run: |
          git clone https://github.com/AlphaCodeSWE/AlphaCode-docs-file.wiki:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync Decision Logs to Wiki
        run: |
          mkdir -p wiki/DecisionLogs
          cp -v docs/decisions/LOG_*.md wiki/DecisionLogs/
          INDEX_FILE="wiki/Registro%20Decisione.md"
          echo "# Registro Decisione" > "$INDEX_FILE"
          echo "" >> "$INDEX_FILE"
          echo "Elenco delle decisioni:" >> "$INDEX_FILE"
          echo "" >> "$INDEX_FILE"
          for file in wiki/DecisionLogs/LOG_*.md; do
            filename=$(basename "$file")
            echo "- [$filename](DecisionLogs/$filename)" >> "$INDEX_FILE"
          done

      - name: Commit and Push Wiki Updates
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync decision logs to Wiki"
            git push
          else
            echo "No changes to commit."
          fi
